name: react_testing_library
version: 1.1.8
description: A Dart unit testing library for OverReact components that mimics the API of the JS react-testing-library
homepage: https://github.com/Workiva/react_testing_library/
documentation: https://workiva.github.io/react_testing_library
environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  color: ">=2.1.1 <4.0.0"
  js: ^0.6.2
  matcher: ^0.12.9
  meta: ^1.1.0
  react: ^6.0.0
  test: ^1.14.4

dev_dependencies:
  build_runner: ^1.7.1
  build_test: ">=0.10.9 <3.0.0"
  build_web_compilers: ^2.9.0
  test_html_builder: ^1.0.0
  workiva_analysis_options: ^1.0.0
